### ISSUE TITLE
Кагда аптимизация на тилифон rEdmi c1?

### ISSUE THREAD

**Issue by giwih** [PANATARA/TypingSpeed#1]
на рЭдми с1 очень говно

**Comment by PANATARA** [comment]
Здравствуй! Мой дорогой подписчик! Оптимизации никогда не будет:)

**Comment by giwih** [comment]
здорово брат! пачиму?

**Comment by giwih** [comment]
**Здравствуйте**  @PANATARA ваша репозитория будет передана модератору на рассмотрение и в течении 24 часов будет вынесен вердикт об удалении репозитории за оскорбительно отношения к пользователям GitHub! Oбжалование вердикта можно будет провести только после его вынеса

**Comment by giwih** [comment]
Здравствуйте @PANATARA  модератор @giwih вынес вердикт об удалении репозитории в случае не выполнений следующих условий в течение 7 дней: Оптимизация сайта TypingSpeed под все линейки смартфонов Xiaomi

**Comment by giwih** [comment]
@PANATARA в течении прошедших 7 дней условия небыли выполнены репозитория будет удалена в ближайшие 24часа
